name: build

on:
  pull_request:
    branches: [main]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 분석의 더 나은 관련성을 위해 얕은 클론을 비활성화해야합니다.

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: gradle

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle 권한 부여
        run: |
          chmod +x ./gradlew

      - name: Node 설치
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Gradle 초기화
        run: |
          ./gradlew clean

      - name: Gradle 테스트
        run: |
          ./gradlew test

      - name: Gradle 빌드
        run: ./gradlew build --exclude-task test --scan --no-daemon --parallel
